# SPDX-FileCopyrightText: 2020, microG Project Team
# SPDX-License-Identifier: CC0-1.0

jobs:
  include:
    - name: "Build"
      language: android
      android:
        components:
          - tools
          - build-tools-28.0.3
          - build-tools-26.0.3
          - android-26
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install ninja-build libunwind8-dev
        - echo y | sdkmanager "ndk;21.3.6528147"
        - echo y | sdkmanager "patcher;v4"
      script:
        - export TERM=dumb
        - jdk_switcher use oraclejdk8
        - ./build.sh
    - name: "REUSE lint"
      language: minimal
      script:
        - docker pull fsfe/reuse:latest
        - docker run -v ${TRAVIS_BUILD_DIR}:/data fsfe/reuse:latest lint
